version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3308:3306
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laraveluser
            MYSQL_PASSWORD: your_mysql_password
            MYSQL_ROOT_PASSWORD: your_mysql_root_password
        networks:
            - laravel_network

networks:
    laravel_network:


volumes:
    db_data:
